config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :students, except: [:new, :destroy]
  get 'signup', to: 'students#new'
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord 
	validates :name, presence: true, length: { minimum: 5, maximum: 50}
	validates :short_name, presence: true, length: { minimum: 2, maximum: 15}
	validates :description, presence: true, length: { minimum: 10, maximum: 300}
	has_many :student_courses
	has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true,
								length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
						uniqueness: { case_sensitive: false },
								length: { maximum: 105 },
								format: { with: VALID_EMAIL_REGEX }
	has_secure_password	
	has_many :student_courses
	has_many :courses, through: :student_courses						
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
	belongs_to :student 
	belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :require_user
	
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= Student.find(session[:student_id]) if session[:student_id]
	end
	
	def logged_in?
	 	!!current_user
	end 

	def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	skip_before_action :require_user, only: [:index] 

  def index
  	@courses = Course.all
  end

  def new
  	
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	skip_before_action :require_user, only: [:new, :create]
	
	def new
		
	end

	def create
		student = Student.find_by(email: params[:logins][:email].downcase)
		if student && student.authenticate(params[:logins][:password])
			session[:student_id] = student.id
			flash[:notice] = "You have successfully logged in"
			redirect_to student
		else
			flash.now[:notice] = "Something was wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:student_id] = nil
		flash[:notice] = "You have successfully logged out"
		redirect_to root_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :require_user
  def about
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

	def create
		course_to_add = Course.find(params[:course_id])
		unless current_user.courses.include?(course_to_add)
			StudentCourse.create(course: course_to_add, student: current_user)
			flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
			redirect_to current_user
		else
			flash[:notice] = "somthing was worng with your enrollment"
			redirect_to root_path		
		end
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :set_student, only: [:show, :edit, :update]
  skip_before_action :require_user, only: [:new, :create]
  before_action :require_same_student, only: [:edit, :update]

  def index
  	@students = Student.all
  end

  def show
  end

  def new
  	@student = Student.new
  end

  def create
  	@student = Student.new(student_params)
  	if @student.save
  		flash[:notice] = "you have successfully signed up"
  		redirect_to @student
  	else
  		render 'new'
  	end
  end

  def edit
  	
  end

  def update
  	if @student.update(student_params)
  		flash[:notice] = "You have successfully updated your profile"
  		redirect_to @student
  	else
  		render 'edit'
  	end

  end

  private

  def set_student
  	@student = Student.find(params[:id])
  end

  def student_params
   	params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end 

  def require_same_student
    if current_user != @sudent 
      flash[:notice] = 'You can only edit your profile'
      redirect_to student_path(current_user)  
    end

    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def session_link
		 	if logged_in?
     		link_to 'Logout', logout_path, method: :delete
     	else 
    		link_to 'Login', login_path
    	end
	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<div class="row">
	<div class="col s12 ">
		<h3 class="center-align">Courses Listing</h3>
	</div>
</div>
<div class="row">
	<% @courses.each do |course| %>
	<div class="col s12 m6">
		<div class="card small blue-grey lighten-3">
			<div class="card-image waves-effect waves-block waves-light">
			<%=image_tag("ca.jpg", class: "activator")%>  
			</div>
			<div class="card-content">
				<span class="card-title activator gray-text text-darken-4"><%= course.short_name %><i class="material-icons right">more_vert</i></span>
				<% if logged_in? && !(current_user.courses.include?(course)) %>
				<p><%= link_to 'ENROLL', course_enroll_path(course_id: course.id), method: :post %></p>
				<% end %>
			</div>
			<div class="card-reveal blue-grey darken-3 white-text">
				<span class="card-title white-text text-darken-4"><%= course.name %>
				<i class="material-icons right">close</i></span>
				<p><%= course.description %></p>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/courses/new.html.erb
<h1> welcome </h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer orange accent-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
          
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2021 Tech University
      <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <% if logged_in? %>
    <li><%= link_to 'View Profile'.html_safe, student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><%= session_link %></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <% if logged_in? %>
    <li><%= link_to 'View Profile'.html_safe, student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><%= session_link %></li>
  </ul>
  <nav class="orange accent-3">
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to 'Tech University', root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to 'Courses', root_path %></li>
          <% if(logged_in?) %>
          <li><%= link_to 'Students', students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#" data-target="dropdown1">
            <% if(logged_in?) %>
              <%= current_user.name %>
            <% else %>
             Account
            <% end %>
            <i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <li><%= link_to 'Courses', root_path %></li>
          <% if(logged_in?) %>
          <li><%= link_to 'Students', students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row white-text">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2">
            <i class="material-icons right white-text cls-btn btn-flat">close</i>
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
      <%= render 'layouts/navigation'%>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
      <%= render 'layouts/footer'%>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
	<div class="row center sign-up-form">
		<div class="col s12 m12 l12">
			<div class="card-panel">
				<h3 class="header">Log in</h3>
				<div class="row">
					<%= form_for(:logins, html: {class: "col s12"}) do |f| %>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :email, placeholder: "Enter your email address", autofocus: true %>
								<%= f.label :email %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.password_field :password, placeholder: "Enter your password"%>
								<%= f.label :password, class: 'active' %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.button'<i class="material-icons right">arrow_forward</i>LOG IN'.html_safe, class: "orange accent-1 waves-effect waves-teal btn-flat right b1" %>
							</div>
						</div>
						<%= link_to '<i class="material-icons left">person_add</i>SIGN UP'.html_safe, signup_path, class: 'left' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
 

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="container">
		<div class="row white-text">
			<div class="col s12 m12 l12">
				<div class="card-panel red lighten-2">
					<i class="material-icons right white-text cls-btn btn-flat">close</i>
					<span class="white-text">
						<b><%= pluralize(obj.errors.count,"error") %></b>
						prohibited your profile from being created
						<ul>
							<% obj.errors.full_messages.each do |message|%>
							<li><%= message %></li>
							<% end %>
						</ul>
					</span>
				</div>
			</div>
		</div>
	</div>
<%end%>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
	<div class="row center sign-up-form">
		<div class="col s12 m12 l12">
			<div class="card-panel">
				<h3 class="header"><%= @student.new_record? ? 'Sign up!' : 'Edit your profile' %></h3>
				<div class="row">
					<%= form_for(@student, html: {class: "col s12"}) do |f| %>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
								<%= f.label :name, class: 'active' %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.text_field :email, placeholder: "Enter your email address", autofocus: true %>
								<%= f.label :email, class: 'active' %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.password_field :password, placeholder: "Choose a password"%>
								<%= f.label :password, class: 'active' %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.password_field :password_confirmation, placeholder: "Confirm your password"%>
								<%= f.label :password_confirmation, class: 'active' %>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>SIGN UP'.html_safe : '<i class="material-icons right">arrow_forward</i>UPDATE'.html_safe, class: "orange accent-1 waves-effect waves-teal btn-flat right b1") %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
 

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
	<div class="col s12 ">
		<h3 class="center-align">Students Directory</h3>
	</div>
</div>
<div class="row">
	<% @students.each do |student| %>
	<div class="col s12 m6">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<span class="card-title">Name: <%= student.name %></span>
				<span>Email: <%= student.email %></span>
				<p>No. of Course Enrollments: 
					<% if student.courses.empty? %>
					None
					<% else %>
					 <%= student.courses.count%>
					<% end %>
				</p>
			</div>
			<div class="card-action">
				<%= link_to 'View Profile', student_path(student), class: "waves-effect waves-light btn" %>
				
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row sign-up-form">
	<div class="col s12 m6 offset-m3">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<span class="card-title">Name: <%= @student.name %></span>
				<span>Email: <%= @student.email %></span>
				<p>No. of Course Enrollments: 
					<% if @student.courses.empty? %>
					None
					<% else %>
					 <%= @student.courses.count %>
					<% end %>
				</p>
			</div>
			<% if(@student == current_user) %>
				<div class="card-action">
					<%= link_to '<i class="material-icons right">create</i>Edit Profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
				</div>
			<% end %>
		</div>
			<% if !@student.courses.empty? %>
				<h4 class="center"><%= pluralize(@student.courses.count,"Course") %></h4>
				<% @student.courses.each do |course|%>
					<div class="card blue-grey lighten-3">
						<div class="card-image waves-effect waves-block waves-light">
						<%=image_tag("ca.jpg", class: "activator")%>  
						</div>
						<div class="card-content">
							<span class="card-title activator gray-text text-darken-4"><%= course.short_name %><i class="material-icons right">more_vert</i></span>
						</div>
						<div class="card-reveal blue-grey darken-3 white-text">
							<span class="card-title white-text text-darken-4"><%= course.name %>
							<i class="material-icons right">close</i></span>
							<p><%= course.description %></p>
						</div>
					</div>
				<% end %>
			<% end %>
	</div>
</div>